import './svg/used.svg';
import './svg/burger.svg';
import './svg/cart.svg';
import './svg/close.svg';
import './svg/close-thin.svg';
import './svg/companies.svg';
import './svg/demand.svg';
import './svg/dots.svg';
import './svg/dropdown.svg';
import './svg/delete.svg';
import './svg/events.svg';
import './svg/edit.svg';
import './svg/filter.svg';
import './svg/filter-2.svg';
import './svg/goods.svg';
import './svg/logo.svg';
import './svg/mail.svg';
import './svg/mail-check.svg';
import './svg/minus.svg';
import './svg/modules.svg';
import './svg/plus.svg';
import './svg/plus-slim.svg';
import './svg/products.svg';
import './svg/rating-open.svg';
import './svg/realty.svg';
import './svg/auction.svg';
import './svg/search.svg';
import './svg/search-thin.svg';
import './svg/services.svg';
import './svg/share.svg';
import './svg/rents.svg';
import './svg/vacancies.svg';
import './svg/no-avatar.svg';
import './svg/user-avatar.svg';
import './svg/user-deleted.svg';
import './svg/settings.svg';
import './svg/view-cards.svg';
import './svg/view-tile.svg';
import './svg/view-tile-big.svg';
import './svg/view-list.svg';
import './svg/view-list-photo.svg';
import './svg/view-map.svg';
import './svg/turn-photo-right.svg';
import './svg/autosearch.svg';
import './svg/comparison.svg';
import './svg/star.svg';
import './svg/views.svg';
import './svg/transport.svg';
import './svg/arrow-left.svg';
import './svg/arrow-right.svg';
import './svg/drag.svg';
import './svg/trash.svg';
import './svg/address.svg';
import './svg/camera.svg';
import './svg/sorting-inc.svg';
import './svg/sorting-dec.svg';
import './svg/anonymus.svg';
import './svg/arrow-back.svg';
import './svg/drag-2.svg';
import './svg/edit-2.svg';
import './svg/category.svg';
import './svg/arrow-left-bold.svg';
import './svg/calendar-done.svg';
import './svg/calendar.svg';
import './svg/support.svg';
import './svg/bed-1-place.svg';
import './svg/bed-2-place.svg';
import './svg/block.svg';
import './svg/voa-logo.svg'
import './svg/voa-print.svg'
import './svg/voa-control-panel.svg'
import './svg/upload_file.svg'
import './svg/voa-trash.svg'
import './svg/voa-pib.svg'
import './svg/voa-reregistration.svg'
import './svg/edit-profile.svg'
import './svg/voa-plus.svg'
import './svg/voa-info.svg'
import './svg/voa-eye.svg'
import './svg/voa-arrow-right.svg'
import './svg/voa-arrow-left.svg'
import './svg/voa-telephone.svg'
import './svg/reregistration-arrow-right.svg'
